apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-application
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
      - name: color-app
        image: 435023700720.dkr.ecr.ap-south-1.amazonaws.com/ak-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80